apiVersion: apps.cloudtruth.com/v1alpha1
kind: KubeTruth
metadata:
  name: kubetruth-sample-short
spec:
  # Default values copied from <project_dir>/helm-charts/kubetruth/values.yaml
  affinity: {}
  appSettings:
    apiKey: 832guQjd.nMpEZa2Xuvup2W2usCOtnGh83RUASFOZ